version: "3.9"

# env_file:
#   - path: .env

services:
  app:
    build: .
    ports:
      - "3333:3333"
    links:
      - db
    command: npm run dev
    depends_on:
      - db
    env_file:
      - fileName: app/.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
  db:
    image: postgres
    env_file:
      - fileName: db/.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
