version: "3.8"

services:
  webapp:
    build: .
    command: npm run dev
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=nataia
      - POSTGRES_DB=edu-control
    ports:
      - 5432:5432
