
################### Student Entity #########################
GET http://localhost:3333/api/v1/students
###
POST http://localhost:3333/api/v1/students
Content-Type: application/json

{
    "firstName": "Marcell",
    "lastName": "Andrade",
    "email": "maarcell@gmail.com",
    "password": "12231238903"
}
###
PUT http://localhost:3333/api/v1/students/clsj04rky0000784ogwws7vcp
Content-Type: application/json

{
    "email":"asdsa@asdas.com"
}
###
DELETE http://localhost:3333/api/v1/students/clsj04rky0000784ogwws7vcp

