################### Student Entity #########################
GET http://localhost:3333/api/v1/students
###
POST http://localhost:3333/api/v1/students
Content-Type: application/json

{
    "firstName": "Marcell",
    "lastName": "Andrade",
    "email": "maarcell@gmail.com",
    "password": "12231238903",

}
###
PUT http://localhost:3333/api/v1/students/clsj04rky0000784ogwws7vcp
Content-Type: application/json

{
    "email":"asdsa@asdas.com"
}
###
DELETE http://localhost:3333/api/v1/students/clsj04rky0000784ogwws7vcp

################### Course Entity #########################

GET http://localhost:3333/api/v1/courses
###
POST http://localhost:3333/api/v1/courses
Content-Type: application/json

{
    "name":"Data Structures"
}
###
PUT http://localhost:3333/api/v1/courses/clsjb8t430000kduz2ef4p2b3
Content-Type: application/json

{
    "name":"Big Data Analisys"
}
###
DELETE http://localhost:3333/api/v1/courses/clsjb8t430000kduz2ef4p2b3

################### Enrollment #########################

POST http://localhost:3333/api/v1/enroll/clsj1rm9l00007exgxfkwgu1o
Content-Type: application/json

{
 "courseID":"clsjbcdwv00006u0i9lgdqloq"
}
###
POST http://localhost:3333/api/v1/unenroll/clsj1rm9l00007exgxfkwgu1o
Content-Type: application/json

{
 "courseID":"clsjbcdwv00006u0i9lgdqloq"
}